apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-configmap
  namespace: processor
data:
  QUEUE_INPUT: "fastfood-soat-terraform-order-to-kitchen.fifo"
  QUEUE_OUTPUT: "fastfood-soat-terraform-kitchen-to-order"
  STORAGE_OUTPUT: "fastfood-soat-terraform-processed-videos"