apiVersion: v1
kind: ConfigMap
metadata:
  name: processor-configmap
  namespace: processor
data:
  QUEUE_INPUT: "hackaton-soat-process"
  QUEUE_OUTPUT: "hackaton-soat-processed"
  STORAGE_OUTPUT: "hackaton-soat-storage"